// <auto-generated />
using System;
using ClarityClinical.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClarityClinical.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClarityClinicalDbContext))]
    [Migration("20261006234520_AddClinicianResponses")]
    partial class AddClinicianResponses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClarityClinical.Domain.Assessments.ClinicalAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_id");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId", "EvaluatedAt");

                    b.ToTable("clinical_assessment", "clinical");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Assessments.ClinicianResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actor_role");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_id");

                    b.Property<string>("ModifiedAction")
                        .HasColumnType("text")
                        .HasColumnName("modified_action");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<string>("RecommendationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("recommendation_key");

                    b.Property<DateTimeOffset>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("response_type");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId", "RecommendationKey", "RespondedAt");

                    b.ToTable("clinician_response", "clinical");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("actor_role");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<Guid?>("DemoSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("demo_session_id");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("NewState")
                        .HasColumnType("text")
                        .HasColumnName("new_state");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PreviousState")
                        .HasColumnType("text")
                        .HasColumnName("previous_state");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RuleVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_version");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("ConsultationId", "OccurredAt");

                    b.ToTable("audit_event", "audit");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Consultations.ClinicalFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("code");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("display_text");

                    b.Property<bool>("IncludeInReasoning")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_reasoning");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_type");

                    b.Property<Guid>("consultation_id")
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_id");

                    b.HasKey("Id");

                    b.HasIndex("consultation_id", "OccurredAt");

                    b.ToTable("clinical_event", "consultations");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Consultations.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.ToTable("consultation", "consultations");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Demo.DemoScenario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClinicianLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("clinician_language");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCanonical")
                        .HasColumnType("boolean")
                        .HasColumnName("is_canonical");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("ScenarioKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("scenario_key");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("setting");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_language");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioKey")
                        .IsUnique();

                    b.ToTable("demo_scenario", "admin");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Demo.DemoScenarioStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClinicalFactCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("clinical_fact_code");

                    b.Property<string>("ClinicalFactDisplayText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("clinical_fact_display_text");

                    b.Property<string>("OriginalText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("original_text");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("SourceLanguage")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_language");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("step_type");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId", "Sequence")
                        .IsUnique();

                    b.ToTable("demo_scenario_step", "admin");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Demo.DemoSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at");

                    b.Property<Guid>("ScenarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("scenario_id");

                    b.Property<string>("VisitorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId")
                        .IsUnique();

                    b.HasIndex("VisitorId", "ExpiresAt");

                    b.ToTable("demo_session", "admin");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Patients.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("given_name");

                    b.HasKey("Id");

                    b.ToTable("patient", "patients");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Assessments.ClinicalAssessment", b =>
                {
                    b.OwnsMany("ClarityClinical.Domain.Assessments.AssessmentCandidate", "Candidates", b1 =>
                        {
                            b1.Property<Guid>("clinical_assessment_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Key")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("key");

                            b1.Property<int>("CurrentScore")
                                .HasColumnType("integer")
                                .HasColumnName("current_score");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.Property<int?>("PreviousScore")
                                .HasColumnType("integer")
                                .HasColumnName("previous_score");

                            b1.Property<string>("ScoreType")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("score_type");

                            b1.HasKey("clinical_assessment_id", "Key");

                            b1.ToTable("assessment_candidate", "clinical");

                            b1.WithOwner()
                                .HasForeignKey("clinical_assessment_id");
                        });

                    b.Navigation("Candidates");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Consultations.ClinicalFact", b =>
                {
                    b.HasOne("ClarityClinical.Domain.Consultations.Consultation", null)
                        .WithMany("Facts")
                        .HasForeignKey("consultation_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClarityClinical.Domain.Demo.DemoScenarioStep", b =>
                {
                    b.HasOne("ClarityClinical.Domain.Demo.DemoScenario", null)
                        .WithMany("Steps")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClarityClinical.Domain.Patients.Patient", b =>
                {
                    b.OwnsMany("ClarityClinical.Domain.Patients.PatientAllergy", "Allergies", b1 =>
                        {
                            b1.Property<Guid>("patient_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("code");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.HasKey("patient_id", "Code");

                            b1.ToTable("patient_allergy", "patients");

                            b1.WithOwner()
                                .HasForeignKey("patient_id");
                        });

                    b.OwnsMany("ClarityClinical.Domain.Patients.PatientCondition", "Conditions", b1 =>
                        {
                            b1.Property<Guid>("patient_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("code");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.HasKey("patient_id", "Code");

                            b1.ToTable("patient_condition", "patients");

                            b1.WithOwner()
                                .HasForeignKey("patient_id");
                        });

                    b.OwnsMany("ClarityClinical.Domain.Patients.PatientMedication", "Medications", b1 =>
                        {
                            b1.Property<Guid>("patient_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("code");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("display_name");

                            b1.HasKey("patient_id", "Code");

                            b1.ToTable("patient_medication", "patients");

                            b1.WithOwner()
                                .HasForeignKey("patient_id");
                        });

                    b.Navigation("Allergies");

                    b.Navigation("Conditions");

                    b.Navigation("Medications");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Consultations.Consultation", b =>
                {
                    b.Navigation("Facts");
                });

            modelBuilder.Entity("ClarityClinical.Domain.Demo.DemoScenario", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
